#! /bin/bash

export TEXTY_HOME="$(dirname $0)"
cd "$TEXTY_HOME"

source lib/init.sh

usage() {
    echo "Usage: $(basename $0) command args..." >&2
    echo "Commands:" >&2
    for exe in $(ls bin) ; do
        echo "  ${exe/texty-}"
    done
}

if [ $# -eq 0 ] ; then
    usage
    exit 1
fi

cmd="$1"
shift

exe="bin/texty-$cmd"
if [ ! -x "$exe" ] ; then
    echo "Unknown command: $cmd" >&2
    usage
    exit 1
fi

exec "$exe" "$@"
