#! /bin/bash

export TEXTY_HOME="$(dirname $0)"
cd "$TEXTY_HOME"

texty_init() {
    source "$TEXTY_HOME/lib/init.sh"
    ME="$(basename $0)"
}
export -f texty_init

texty_init

usage() {
    echo "Usage: $ME command args..." >&2
    echo "Commands:" >&2
    for exe in $(ls bin) ; do
        echo "  ${exe/texty-}"
    done
    exit 1
}

[ $# -eq 0 ] && usage

cmd="$1"
shift

exe="bin/texty-$cmd"
if [ ! -x "$exe" ] ; then
    echo "Unknown command: $cmd" >&2
    usage
fi

exec "$exe" "$@"
